# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ClockUi.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(345, 259)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_2.setHorizontalSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(2, 2, 2, 2)
        self.gridLayout.setObjectName("gridLayout")
        self.S_7 = QtWidgets.QLabel(Dialog)
        self.S_7.setObjectName("S_7")
        self.gridLayout.addWidget(self.S_7, 0, 7, 1, 1)
        self.S_5 = QtWidgets.QLabel(Dialog)
        self.S_5.setObjectName("S_5")
        self.gridLayout.addWidget(self.S_5, 0, 5, 1, 1)
        self.S_6 = QtWidgets.QLabel(Dialog)
        self.S_6.setObjectName("S_6")
        self.gridLayout.addWidget(self.S_6, 0, 6, 1, 1)
        self.S_4 = QtWidgets.QLabel(Dialog)
        self.S_4.setObjectName("S_4")
        self.gridLayout.addWidget(self.S_4, 0, 4, 1, 1)
        self.S_3 = QtWidgets.QLabel(Dialog)
        self.S_3.setObjectName("S_3")
        self.gridLayout.addWidget(self.S_3, 0, 3, 1, 1)
        self.S_1 = QtWidgets.QLabel(Dialog)
        self.S_1.setObjectName("S_1")
        self.gridLayout.addWidget(self.S_1, 0, 1, 1, 1)
        self.S_2 = QtWidgets.QLabel(Dialog)
        self.S_2.setObjectName("S_2")
        self.gridLayout.addWidget(self.S_2, 0, 2, 1, 1)
        self.S_13 = QtWidgets.QLabel(Dialog)
        self.S_13.setObjectName("S_13")
        self.gridLayout.addWidget(self.S_13, 0, 13, 1, 1)
        self.S_15 = QtWidgets.QLabel(Dialog)
        self.S_15.setObjectName("S_15")
        self.gridLayout.addWidget(self.S_15, 0, 15, 1, 1)
        self.S_16 = QtWidgets.QLabel(Dialog)
        self.S_16.setObjectName("S_16")
        self.gridLayout.addWidget(self.S_16, 0, 16, 1, 1)
        self.S_23 = QtWidgets.QLabel(Dialog)
        self.S_23.setObjectName("S_23")
        self.gridLayout.addWidget(self.S_23, 7, 16, 1, 1)
        self.S_28 = QtWidgets.QLabel(Dialog)
        self.S_28.setObjectName("S_28")
        self.gridLayout.addWidget(self.S_28, 12, 16, 1, 1)
        self.S_29 = QtWidgets.QLabel(Dialog)
        self.S_29.setObjectName("S_29")
        self.gridLayout.addWidget(self.S_29, 13, 16, 1, 1)
        self.S_18 = QtWidgets.QLabel(Dialog)
        self.S_18.setObjectName("S_18")
        self.gridLayout.addWidget(self.S_18, 2, 16, 1, 1)
        self.S_17 = QtWidgets.QLabel(Dialog)
        self.S_17.setObjectName("S_17")
        self.gridLayout.addWidget(self.S_17, 1, 16, 1, 1)
        self.S_21 = QtWidgets.QLabel(Dialog)
        self.S_21.setObjectName("S_21")
        self.gridLayout.addWidget(self.S_21, 5, 16, 1, 1)
        self.S_20 = QtWidgets.QLabel(Dialog)
        self.S_20.setObjectName("S_20")
        self.gridLayout.addWidget(self.S_20, 4, 16, 1, 1)
        self.S_24 = QtWidgets.QLabel(Dialog)
        self.S_24.setObjectName("S_24")
        self.gridLayout.addWidget(self.S_24, 8, 16, 1, 1)
        self.S_22 = QtWidgets.QLabel(Dialog)
        self.S_22.setObjectName("S_22")
        self.gridLayout.addWidget(self.S_22, 6, 16, 1, 1)
        self.S_19 = QtWidgets.QLabel(Dialog)
        self.S_19.setObjectName("S_19")
        self.gridLayout.addWidget(self.S_19, 3, 16, 1, 1)
        self.S_26 = QtWidgets.QLabel(Dialog)
        self.S_26.setObjectName("S_26")
        self.gridLayout.addWidget(self.S_26, 10, 16, 1, 1)
        self.S_25 = QtWidgets.QLabel(Dialog)
        self.S_25.setObjectName("S_25")
        self.gridLayout.addWidget(self.S_25, 9, 16, 1, 1)
        self.S_27 = QtWidgets.QLabel(Dialog)
        self.S_27.setObjectName("S_27")
        self.gridLayout.addWidget(self.S_27, 11, 16, 1, 1)
        self.S_14 = QtWidgets.QLabel(Dialog)
        self.S_14.setObjectName("S_14")
        self.gridLayout.addWidget(self.S_14, 0, 14, 1, 1)
        self.S_8 = QtWidgets.QLabel(Dialog)
        self.S_8.setObjectName("S_8")
        self.gridLayout.addWidget(self.S_8, 0, 8, 1, 1)
        self.S = QtWidgets.QLabel(Dialog)
        self.S.setObjectName("S")
        self.gridLayout.addWidget(self.S, 0, 0, 1, 1)
        self.S_9 = QtWidgets.QLabel(Dialog)
        self.S_9.setObjectName("S_9")
        self.gridLayout.addWidget(self.S_9, 0, 9, 1, 1)
        self.S_10 = QtWidgets.QLabel(Dialog)
        self.S_10.setObjectName("S_10")
        self.gridLayout.addWidget(self.S_10, 0, 10, 1, 1)
        self.S_12 = QtWidgets.QLabel(Dialog)
        self.S_12.setObjectName("S_12")
        self.gridLayout.addWidget(self.S_12, 0, 12, 1, 1)
        self.S_11 = QtWidgets.QLabel(Dialog)
        self.S_11.setObjectName("S_11")
        self.gridLayout.addWidget(self.S_11, 0, 11, 1, 1)
        self.S_30 = QtWidgets.QLabel(Dialog)
        self.S_30.setObjectName("S_30")
        self.gridLayout.addWidget(self.S_30, 14, 16, 1, 1)
        self.S_31 = QtWidgets.QLabel(Dialog)
        self.S_31.setObjectName("S_31")
        self.gridLayout.addWidget(self.S_31, 14, 15, 1, 1)
        self.S_32 = QtWidgets.QLabel(Dialog)
        self.S_32.setObjectName("S_32")
        self.gridLayout.addWidget(self.S_32, 14, 14, 1, 1)
        self.S_33 = QtWidgets.QLabel(Dialog)
        self.S_33.setObjectName("S_33")
        self.gridLayout.addWidget(self.S_33, 14, 13, 1, 1)
        self.S_34 = QtWidgets.QLabel(Dialog)
        self.S_34.setObjectName("S_34")
        self.gridLayout.addWidget(self.S_34, 14, 12, 1, 1)
        self.S_35 = QtWidgets.QLabel(Dialog)
        self.S_35.setObjectName("S_35")
        self.gridLayout.addWidget(self.S_35, 14, 11, 1, 1)
        self.S_36 = QtWidgets.QLabel(Dialog)
        self.S_36.setObjectName("S_36")
        self.gridLayout.addWidget(self.S_36, 14, 10, 1, 1)
        self.S_38 = QtWidgets.QLabel(Dialog)
        self.S_38.setObjectName("S_38")
        self.gridLayout.addWidget(self.S_38, 14, 8, 1, 1)
        self.S_37 = QtWidgets.QLabel(Dialog)
        self.S_37.setObjectName("S_37")
        self.gridLayout.addWidget(self.S_37, 14, 9, 1, 1)
        self.S_39 = QtWidgets.QLabel(Dialog)
        self.S_39.setObjectName("S_39")
        self.gridLayout.addWidget(self.S_39, 14, 7, 1, 1)
        self.S_40 = QtWidgets.QLabel(Dialog)
        self.S_40.setObjectName("S_40")
        self.gridLayout.addWidget(self.S_40, 14, 6, 1, 1)
        self.S_41 = QtWidgets.QLabel(Dialog)
        self.S_41.setObjectName("S_41")
        self.gridLayout.addWidget(self.S_41, 14, 5, 1, 1)
        self.S_42 = QtWidgets.QLabel(Dialog)
        self.S_42.setObjectName("S_42")
        self.gridLayout.addWidget(self.S_42, 14, 4, 1, 1)
        self.S_43 = QtWidgets.QLabel(Dialog)
        self.S_43.setObjectName("S_43")
        self.gridLayout.addWidget(self.S_43, 14, 3, 1, 1)
        self.S_44 = QtWidgets.QLabel(Dialog)
        self.S_44.setObjectName("S_44")
        self.gridLayout.addWidget(self.S_44, 14, 2, 1, 1)
        self.S_45 = QtWidgets.QLabel(Dialog)
        self.S_45.setObjectName("S_45")
        self.gridLayout.addWidget(self.S_45, 14, 1, 1, 1)
        self.S_46 = QtWidgets.QLabel(Dialog)
        self.S_46.setObjectName("S_46")
        self.gridLayout.addWidget(self.S_46, 14, 0, 1, 1)
        self.S_47 = QtWidgets.QLabel(Dialog)
        self.S_47.setObjectName("S_47")
        self.gridLayout.addWidget(self.S_47, 13, 0, 1, 1)
        self.S_48 = QtWidgets.QLabel(Dialog)
        self.S_48.setObjectName("S_48")
        self.gridLayout.addWidget(self.S_48, 12, 0, 1, 1)
        self.S_49 = QtWidgets.QLabel(Dialog)
        self.S_49.setObjectName("S_49")
        self.gridLayout.addWidget(self.S_49, 11, 0, 1, 1)
        self.S_50 = QtWidgets.QLabel(Dialog)
        self.S_50.setObjectName("S_50")
        self.gridLayout.addWidget(self.S_50, 10, 0, 1, 1)
        self.S_51 = QtWidgets.QLabel(Dialog)
        self.S_51.setObjectName("S_51")
        self.gridLayout.addWidget(self.S_51, 9, 0, 1, 1)
        self.S_52 = QtWidgets.QLabel(Dialog)
        self.S_52.setObjectName("S_52")
        self.gridLayout.addWidget(self.S_52, 8, 0, 1, 1)
        self.S_53 = QtWidgets.QLabel(Dialog)
        self.S_53.setObjectName("S_53")
        self.gridLayout.addWidget(self.S_53, 7, 0, 1, 1)
        self.S_54 = QtWidgets.QLabel(Dialog)
        self.S_54.setObjectName("S_54")
        self.gridLayout.addWidget(self.S_54, 6, 0, 1, 1)
        self.S_55 = QtWidgets.QLabel(Dialog)
        self.S_55.setObjectName("S_55")
        self.gridLayout.addWidget(self.S_55, 5, 0, 1, 1)
        self.S_56 = QtWidgets.QLabel(Dialog)
        self.S_56.setObjectName("S_56")
        self.gridLayout.addWidget(self.S_56, 4, 0, 1, 1)
        self.S_57 = QtWidgets.QLabel(Dialog)
        self.S_57.setObjectName("S_57")
        self.gridLayout.addWidget(self.S_57, 3, 0, 1, 1)
        self.S_58 = QtWidgets.QLabel(Dialog)
        self.S_58.setObjectName("S_58")
        self.gridLayout.addWidget(self.S_58, 2, 0, 1, 1)
        self.S_59 = QtWidgets.QLabel(Dialog)
        self.S_59.setObjectName("S_59")
        self.gridLayout.addWidget(self.S_59, 1, 0, 1, 1)
        self.F1_1 = QtWidgets.QLabel(Dialog)
        self.F1_1.setObjectName("F1_1")
        self.gridLayout.addWidget(self.F1_1, 1, 1, 3, 4)
        self.F1_2 = QtWidgets.QLabel(Dialog)
        self.F1_2.setObjectName("F1_2")
        self.gridLayout.addWidget(self.F1_2, 4, 1, 3, 4)
        self.F_2 = QtWidgets.QLabel(Dialog)
        self.F_2.setObjectName("F_2")
        self.gridLayout.addWidget(self.F_2, 1, 5, 6, 4)
        self.F_3 = QtWidgets.QLabel(Dialog)
        self.F_3.setObjectName("F_3")
        self.gridLayout.addWidget(self.F_3, 7, 1, 7, 8)
        self.F_5 = QtWidgets.QLabel(Dialog)
        self.F_5.setObjectName("F_5")
        self.gridLayout.addWidget(self.F_5, 1, 9, 13, 7)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.S_7.setText(_translate("Dialog", ""))
        self.S_5.setText(_translate("Dialog", ""))
        self.S_6.setText(_translate("Dialog", ""))
        self.S_4.setText(_translate("Dialog", ""))
        self.S_3.setText(_translate("Dialog", ""))
        self.S_1.setText(_translate("Dialog", ""))
        self.S_2.setText(_translate("Dialog", ""))
        self.S_13.setText(_translate("Dialog", ""))
        self.S_15.setText(_translate("Dialog", ""))
        self.S_16.setText(_translate("Dialog", ""))
        self.S_23.setText(_translate("Dialog", ""))
        self.S_28.setText(_translate("Dialog", ""))
        self.S_29.setText(_translate("Dialog", ""))
        self.S_18.setText(_translate("Dialog", ""))
        self.S_17.setText(_translate("Dialog", ""))
        self.S_21.setText(_translate("Dialog", ""))
        self.S_20.setText(_translate("Dialog", ""))
        self.S_24.setText(_translate("Dialog", ""))
        self.S_22.setText(_translate("Dialog", ""))
        self.S_19.setText(_translate("Dialog", ""))
        self.S_26.setText(_translate("Dialog", ""))
        self.S_25.setText(_translate("Dialog", ""))
        self.S_27.setText(_translate("Dialog", ""))
        self.S_14.setText(_translate("Dialog", ""))
        self.S_8.setText(_translate("Dialog", ""))
        self.S.setText(_translate("Dialog", ""))
        self.S_9.setText(_translate("Dialog", ""))
        self.S_10.setText(_translate("Dialog", ""))
        self.S_12.setText(_translate("Dialog", ""))
        self.S_11.setText(_translate("Dialog", ""))
        self.S_30.setText(_translate("Dialog", ""))
        self.S_31.setText(_translate("Dialog", ""))
        self.S_32.setText(_translate("Dialog", ""))
        self.S_33.setText(_translate("Dialog", ""))
        self.S_34.setText(_translate("Dialog", ""))
        self.S_35.setText(_translate("Dialog", ""))
        self.S_36.setText(_translate("Dialog", ""))
        self.S_38.setText(_translate("Dialog", ""))
        self.S_37.setText(_translate("Dialog", ""))
        self.S_39.setText(_translate("Dialog", ""))
        self.S_40.setText(_translate("Dialog", ""))
        self.S_41.setText(_translate("Dialog", ""))
        self.S_42.setText(_translate("Dialog", ""))
        self.S_43.setText(_translate("Dialog", ""))
        self.S_44.setText(_translate("Dialog", ""))
        self.S_45.setText(_translate("Dialog", ""))
        self.S_46.setText(_translate("Dialog", ""))
        self.S_47.setText(_translate("Dialog", ""))
        self.S_48.setText(_translate("Dialog", ""))
        self.S_49.setText(_translate("Dialog", ""))
        self.S_50.setText(_translate("Dialog", ""))
        self.S_51.setText(_translate("Dialog", ""))
        self.S_52.setText(_translate("Dialog", ""))
        self.S_53.setText(_translate("Dialog", ""))
        self.S_54.setText(_translate("Dialog", ""))
        self.S_55.setText(_translate("Dialog", ""))
        self.S_56.setText(_translate("Dialog", ""))
        self.S_57.setText(_translate("Dialog", ""))
        self.S_58.setText(_translate("Dialog", ""))
        self.S_59.setText(_translate("Dialog", ""))
        self.F1_1.setText(_translate("Dialog", ""))
        self.F1_2.setText(_translate("Dialog", ""))
        self.F_2.setText(_translate("Dialog", ""))
        self.F_3.setText(_translate("Dialog", ""))
        self.F_5.setText(_translate("Dialog", ""))

